version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    healthcheck:
      test: ["CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 20s
      retries: 30
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - fullcycle

  node:
    build:
      context: ./node
    container_name: node
    volumes:
    - ./node:/usr/src/app
    - /usr/src/app/node_modules

    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fullcycle

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      node:
        condition: service_started
    networks:
      - fullcycle

volumes:
  mysql-data:

networks:
  fullcycle:
    driver: bridge
